name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -name: print greeting
      run: echo "hello"
      -name: print goodbyr
      run: echo "hi"
